### ISSUE TITLE
Upgrade to latest Hyrax

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#93]
### Descriptive summary

Please update Hyrax to the latest version/commit in 2.0-alpha.

### Rationale

Staying up to date with Hyrax development.

**Comment by hweng** [comment]
@mcritchlow After upgraded, I got 73 test failure. Basically they all point to `Failure/Error: @search_state ||= Hyrax::SearchState.new(self)`

Looking into hyrax and horton, I think that's because there were the exactly same methods copied over to our local app, and the #search_state method was removed from hyrax recently:
https://github.com/projecthydra-labs/hyrax/commit/e23b9c2e86ef177543d01a64ff7184d309ffc76c

For example the failure:
 ```
72) Create a UcsdAgent a logged in user should be able to create agent that links a closeMatch URL
      Failure/Error: @search_state ||= Hyrax::SearchState.new(self)

      ActionView::Template::Error:
        wrong number of arguments (given 1, expected 2..3)
      # ./app/controllers/hyrax/controller.rb:38:in `new'
      # ./app/controllers/hyrax/controller.rb:38:in `search_state'
      # ./app/views/catalog/_search_form.html.erb:2:in `block in _app_views_catalog__search_form_html_erb__589929521283573638_70152744767900'
      # ./app/views/catalog/_search_form.html.erb:1:in `_app_views_catalog__search_form_html_erb__589929521283573638_70152744767900'
      # ./app/controllers/application_controller.rb:13:in `anonymous_user'
      # ./spec/support/features/session_helpers.rb:7:in `sign_in'
      # ./spec/features/ucsd_agent_spec.rb:14:in `block (3 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # ArgumentError:
      #   wrong number of arguments (given 1, expected 2..3)
      #   ./app/controllers/hyrax/controller.rb:38:in `new'
```

**Comment by hweng** [comment]
And also got 7 errors in batch_import_job.rb, such as 
```
7) BatchImportJob #perform Excel XL metadata source when visibility is passed sets public read access
     Failure/Error: status << work_actor.create(env)

     ActiveJob::SerializationError:
       Unsupported argument type: RDF::URI
     # ./app/jobs/ingest_work_job.rb:30:in `block in perform'
     # ./app/jobs/ingest_work_job.rb:15:in `each'
     # ./app/jobs/ingest_work_job.rb:15:in `perform'
     # ./lib/import/tabular_importer.rb:95:in `import'
     # ./app/jobs/batch_import_job.rb:46:in `create'
     # ./app/jobs/batch_import_job.rb:18:in `perform'
     # ./spec/jobs/batch_import_job_spec.rb:29:in `block (3 levels) in <top (required)>'
     # ./spec/jobs/batch_import_job_spec.rb:73:in `block (5 levels) in <top (required)>'
```

**Comment by lsitu** [comment]
@hweng I think there is some historical reasons for the controller class there and we always need to refactor it when moving forward with the changes in Hyrax. Please remove it if it's not necessary. Thanks.

**Comment by hweng** [comment]
@lsitu The `Failure/Error: @search_state ||= Hyrax::SearchState.new(self)` caused by controller class got fixed.
There are 7 new failures caused by batch ingest work.
